Avoid to pre-pull the approved images
The approved image is used as image volume, and currently there is a bug
in kind that doesn't allow and find correctly the image.

Example of the error:

Error: failed to mount image volume: failed to get image from containerd "sha256:d8b185fd14657c001b04d2dd7c5f6271e5add9eb5fdea5defd4f2f7ac0147dde": image "docker.io/library/import-2026-01-29@sha256:8dd68527430ccb2e9357ace2c58ee90aafa4a1811711e232a6df83701ff9d4ec": not found

While we investigate the issue, let's skip the pre-pull of the approved
image.

Signed-off-by: Alice Frosi <afrosi@redhat.com>